//// DO NOT EDIT.
//// swift-format-ignore-file
//// swiftlint:disable all
////
//// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
//// Source: user.proto
////
//// For information on using the generated types, please see the documentation:
////   https://github.com/grpc/grpc-swift
//
//import GRPCCore
//import GRPCProtobuf
//
//// MARK: - user.UserService
//
///// Namespace containing generated types for the "user.UserService" service.
//@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
//public enum User_UserService: Sendable {
//    /// Service descriptor for the "user.UserService" service.
//    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserService")
//    /// Namespace for method metadata.
//    public enum Method: Sendable {
//        /// Namespace for "GetUserProfile" metadata.
//        public enum GetUserProfile: Sendable {
//            /// Request type for "GetUserProfile".
//            public typealias Input = User_UserRequest
//            /// Response type for "GetUserProfile".
//            public typealias Output = User_UserResponse
//            /// Descriptor for "GetUserProfile".
//            public static let descriptor = GRPCCore.MethodDescriptor(
//                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserService"),
//                method: "GetUserProfile",
//                type: .unary
//            )
//        }
//        /// Namespace for "GetAllUsers" metadata.
//        public enum GetAllUsers: Sendable {
//            /// Request type for "GetAllUsers".
//            public typealias Input = User_EmptyRequest
//            /// Response type for "GetAllUsers".
//            public typealias Output = User_UserListResponse
//            /// Descriptor for "GetAllUsers".
//            public static let descriptor = GRPCCore.MethodDescriptor(
//                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserService"),
//                method: "GetAllUsers",
//                type: .unary
//            )
//        }
//        /// Namespace for "GetCategories" metadata.
//        public enum GetCategories: Sendable {
//            /// Request type for "GetCategories".
//            public typealias Input = User_GetCategoriesRequest
//            /// Response type for "GetCategories".
//            public typealias Output = User_GetCategoriesResponse
//            /// Descriptor for "GetCategories".
//            public static let descriptor = GRPCCore.MethodDescriptor(
//                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserService"),
//                method: "GetCategories",
//                type: .unary
//            )
//        }
//        /// Descriptors for all methods in the "user.UserService" service.
//        public static let descriptors: [GRPCCore.MethodDescriptor] = [
//            GetUserProfile.descriptor,
//            GetAllUsers.descriptor,
//            GetCategories.descriptor
//        ]
//    }
//}
//
//@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
//extension GRPCCore.ServiceDescriptor {
//    /// Service descriptor for the "user.UserService" service.
//    public static let user_UserService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserService")
//}
//
//// MARK: user.UserService (client)
//
//@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
//extension User_UserService {
//    /// Generated client protocol for the "user.UserService" service.
//    ///
//    /// You don't need to implement this protocol directly, use the generated
//    /// implementation, ``Client``.
//    public protocol ClientProtocol: Sendable {
//        /// Call the "GetUserProfile" method.
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_UserRequest` message.
//        ///   - serializer: A serializer for `User_UserRequest` messages.
//        ///   - deserializer: A deserializer for `User_UserResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        func getUserProfile<Result>(
//            request: GRPCCore.ClientRequest<User_UserRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_UserRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_UserResponse>,
//            options: GRPCCore.CallOptions,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserResponse>) async throws -> Result
//        ) async throws -> Result where Result: Sendable
//
//        /// Call the "GetAllUsers" method.
//        ///
//        /// > Source IDL Documentation:
//        /// >
//        /// > New RPC method to return a list of users
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_EmptyRequest` message.
//        ///   - serializer: A serializer for `User_EmptyRequest` messages.
//        ///   - deserializer: A deserializer for `User_UserListResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        func getAllUsers<Result>(
//            request: GRPCCore.ClientRequest<User_EmptyRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_EmptyRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_UserListResponse>,
//            options: GRPCCore.CallOptions,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserListResponse>) async throws -> Result
//        ) async throws -> Result where Result: Sendable
//
//        /// Call the "GetCategories" method.
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_GetCategoriesRequest` message.
//        ///   - serializer: A serializer for `User_GetCategoriesRequest` messages.
//        ///   - deserializer: A deserializer for `User_GetCategoriesResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        func getCategories<Result>(
//            request: GRPCCore.ClientRequest<User_GetCategoriesRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_GetCategoriesRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_GetCategoriesResponse>,
//            options: GRPCCore.CallOptions,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetCategoriesResponse>) async throws -> Result
//        ) async throws -> Result where Result: Sendable
//    }
//
//    /// Generated client for the "user.UserService" service.
//    ///
//    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
//    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
//    /// means of communication with the remote peer.
//    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
//        private let client: GRPCCore.GRPCClient<Transport>
//
//        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
//        ///
//        /// - Parameters:
//        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
//        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
//            self.client = client
//        }
//
//        /// Call the "GetUserProfile" method.
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_UserRequest` message.
//        ///   - serializer: A serializer for `User_UserRequest` messages.
//        ///   - deserializer: A deserializer for `User_UserResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        public func getUserProfile<Result>(
//            request: GRPCCore.ClientRequest<User_UserRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_UserRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_UserResponse>,
//            options: GRPCCore.CallOptions = .defaults,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserResponse>) async throws -> Result = { response in
//                try response.message
//            }
//        ) async throws -> Result where Result: Sendable {
//            try await self.client.unary(
//                request: request,
//                descriptor: User_UserService.Method.GetUserProfile.descriptor,
//                serializer: serializer,
//                deserializer: deserializer,
//                options: options,
//                onResponse: handleResponse
//            )
//        }
//
//        /// Call the "GetAllUsers" method.
//        ///
//        /// > Source IDL Documentation:
//        /// >
//        /// > New RPC method to return a list of users
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_EmptyRequest` message.
//        ///   - serializer: A serializer for `User_EmptyRequest` messages.
//        ///   - deserializer: A deserializer for `User_UserListResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        public func getAllUsers<Result>(
//            request: GRPCCore.ClientRequest<User_EmptyRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_EmptyRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_UserListResponse>,
//            options: GRPCCore.CallOptions = .defaults,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserListResponse>) async throws -> Result = { response in
//                try response.message
//            }
//        ) async throws -> Result where Result: Sendable {
//            try await self.client.unary(
//                request: request,
//                descriptor: User_UserService.Method.GetAllUsers.descriptor,
//                serializer: serializer,
//                deserializer: deserializer,
//                options: options,
//                onResponse: handleResponse
//            )
//        }
//
//        /// Call the "GetCategories" method.
//        ///
//        /// - Parameters:
//        ///   - request: A request containing a single `User_GetCategoriesRequest` message.
//        ///   - serializer: A serializer for `User_GetCategoriesRequest` messages.
//        ///   - deserializer: A deserializer for `User_GetCategoriesResponse` messages.
//        ///   - options: Options to apply to this RPC.
//        ///   - handleResponse: A closure which handles the response, the result of which is
//        ///       returned to the caller. Returning from the closure will cancel the RPC if it
//        ///       hasn't already finished.
//        /// - Returns: The result of `handleResponse`.
//        public func getCategories<Result>(
//            request: GRPCCore.ClientRequest<User_GetCategoriesRequest>,
//            serializer: some GRPCCore.MessageSerializer<User_GetCategoriesRequest>,
//            deserializer: some GRPCCore.MessageDeserializer<User_GetCategoriesResponse>,
//            options: GRPCCore.CallOptions = .defaults,
//            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetCategoriesResponse>) async throws -> Result = { response in
//                try response.message
//            }
//        ) async throws -> Result where Result: Sendable {
//            try await self.client.unary(
//                request: request,
//                descriptor: User_UserService.Method.GetCategories.descriptor,
//                serializer: serializer,
//                deserializer: deserializer,
//                options: options,
//                onResponse: handleResponse
//            )
//        }
//    }
//}
//
//// Helpers providing default arguments to 'ClientProtocol' methods.
//@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
//extension User_UserService.ClientProtocol {
//    /// Call the "GetUserProfile" method.
//    ///
//    /// - Parameters:
//    ///   - request: A request containing a single `User_UserRequest` message.
//    ///   - options: Options to apply to this RPC.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getUserProfile<Result>(
//        request: GRPCCore.ClientRequest<User_UserRequest>,
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        try await self.getUserProfile(
//            request: request,
//            serializer: GRPCProtobuf.ProtobufSerializer<User_UserRequest>(),
//            deserializer: GRPCProtobuf.ProtobufDeserializer<User_UserResponse>(),
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//
//    /// Call the "GetAllUsers" method.
//    ///
//    /// > Source IDL Documentation:
//    /// >
//    /// > New RPC method to return a list of users
//    ///
//    /// - Parameters:
//    ///   - request: A request containing a single `User_EmptyRequest` message.
//    ///   - options: Options to apply to this RPC.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getAllUsers<Result>(
//        request: GRPCCore.ClientRequest<User_EmptyRequest>,
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserListResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        try await self.getAllUsers(
//            request: request,
//            serializer: GRPCProtobuf.ProtobufSerializer<User_EmptyRequest>(),
//            deserializer: GRPCProtobuf.ProtobufDeserializer<User_UserListResponse>(),
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//
//    /// Call the "GetCategories" method.
//    ///
//    /// - Parameters:
//    ///   - request: A request containing a single `User_GetCategoriesRequest` message.
//    ///   - options: Options to apply to this RPC.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getCategories<Result>(
//        request: GRPCCore.ClientRequest<User_GetCategoriesRequest>,
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetCategoriesResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        try await self.getCategories(
//            request: request,
//            serializer: GRPCProtobuf.ProtobufSerializer<User_GetCategoriesRequest>(),
//            deserializer: GRPCProtobuf.ProtobufDeserializer<User_GetCategoriesResponse>(),
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//}
//
//// Helpers providing sugared APIs for 'ClientProtocol' methods.
//@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
//extension User_UserService.ClientProtocol {
//    /// Call the "GetUserProfile" method.
//    ///
//    /// - Parameters:
//    ///   - message: request message to send.
//    ///   - metadata: Additional metadata to send, defaults to empty.
//    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getUserProfile<Result>(
//        _ message: User_UserRequest,
//        metadata: GRPCCore.Metadata = [:],
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        let request = GRPCCore.ClientRequest<User_UserRequest>(
//            message: message,
//            metadata: metadata
//        )
//        return try await self.getUserProfile(
//            request: request,
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//
//    /// Call the "GetAllUsers" method.
//    ///
//    /// > Source IDL Documentation:
//    /// >
//    /// > New RPC method to return a list of users
//    ///
//    /// - Parameters:
//    ///   - message: request message to send.
//    ///   - metadata: Additional metadata to send, defaults to empty.
//    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getAllUsers<Result>(
//        _ message: User_EmptyRequest,
//        metadata: GRPCCore.Metadata = [:],
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UserListResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        let request = GRPCCore.ClientRequest<User_EmptyRequest>(
//            message: message,
//            metadata: metadata
//        )
//        return try await self.getAllUsers(
//            request: request,
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//
//    /// Call the "GetCategories" method.
//    ///
//    /// - Parameters:
//    ///   - message: request message to send.
//    ///   - metadata: Additional metadata to send, defaults to empty.
//    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
//    ///   - handleResponse: A closure which handles the response, the result of which is
//    ///       returned to the caller. Returning from the closure will cancel the RPC if it
//    ///       hasn't already finished.
//    /// - Returns: The result of `handleResponse`.
//    public func getCategories<Result>(
//        _ message: User_GetCategoriesRequest,
//        metadata: GRPCCore.Metadata = [:],
//        options: GRPCCore.CallOptions = .defaults,
//        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetCategoriesResponse>) async throws -> Result = { response in
//            try response.message
//        }
//    ) async throws -> Result where Result: Sendable {
//        let request = GRPCCore.ClientRequest<User_GetCategoriesRequest>(
//            message: message,
//            metadata: metadata
//        )
//        return try await self.getCategories(
//            request: request,
//            options: options,
//            onResponse: handleResponse
//        )
//    }
//}
