//// DO NOT EDIT.
//// swift-format-ignore-file
//// swiftlint:disable all
////
//// Generated by the Swift generator plugin for the protocol buffer compiler.
//// Source: user.proto
////
//// For information on using the generated types, please see the documentation:
////   https://github.com/apple/swift-protobuf/
//
//import SwiftProtobuf
//
//// If the compiler emits an error on this type, it is because this file
//// was generated by a version of the `protoc` Swift plug-in that is
//// incompatible with the version of SwiftProtobuf to which you are linking.
//// Please ensure that you are building against the same version of the API
//// that was used to generate this file.
//fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
//  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
//  typealias Version = _2
//}
//
///// Request message (can be empty if you want to fetch everyone)
//public nonisolated struct User_EmptyRequest: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
///// Single user profile data
//public nonisolated struct User_UserResponse: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var userID: String = String()
//
//  public var name: String = String()
//
//  public var email: String = String()
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
///// Wrapping message that returns an array/list of users
//public nonisolated struct User_UserListResponse: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  /// 'repeated' indicates an Array/List in gRPC
//  public var users: [User_UserResponse] = []
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
///// Keep your old UserRequest message down here if needed for GetUserProfile
//public nonisolated struct User_UserRequest: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var userID: String = String()
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
//public nonisolated struct User_GetCategoriesRequest: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
//public nonisolated struct User_Category: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var id: String = String()
//
//  public var name: String = String()
//
//  public var icon: String = String()
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
//public nonisolated struct User_GetCategoriesResponse: Sendable {
//  // SwiftProtobuf.Message conformance is added in an extension below. See the
//  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
//  // methods supported on all messages.
//
//  public var categories: [User_Category] = []
//
//  public var unknownFields = SwiftProtobuf.UnknownStorage()
//
//  public init() {}
//}
//
//// MARK: - Code below here is support for the SwiftProtobuf runtime.
//
//fileprivate nonisolated let _protobuf_package = "user"
//
//nonisolated extension User_EmptyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".EmptyRequest"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    // Load everything into unknown fields
//    while try decoder.nextFieldNumber() != nil {}
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_EmptyRequest, rhs: User_EmptyRequest) -> Bool {
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_UserResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".UserResponse"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{1}name\0\u{1}email\0")
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    while let fieldNumber = try decoder.nextFieldNumber() {
//      // The use of inline closures is to circumvent an issue where the compiler
//      // allocates stack space for every case branch when no optimizations are
//      // enabled. https://github.com/apple/swift-protobuf/issues/1034
//      switch fieldNumber {
//      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
//      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
//      case 3: try { try decoder.decodeSingularStringField(value: &self.email) }()
//      default: break
//      }
//    }
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    if !self.userID.isEmpty {
//      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
//    }
//    if !self.name.isEmpty {
//      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
//    }
//    if !self.email.isEmpty {
//      try visitor.visitSingularStringField(value: self.email, fieldNumber: 3)
//    }
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_UserResponse, rhs: User_UserResponse) -> Bool {
//    if lhs.userID != rhs.userID {return false}
//    if lhs.name != rhs.name {return false}
//    if lhs.email != rhs.email {return false}
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_UserListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".UserListResponse"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}users\0")
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    while let fieldNumber = try decoder.nextFieldNumber() {
//      // The use of inline closures is to circumvent an issue where the compiler
//      // allocates stack space for every case branch when no optimizations are
//      // enabled. https://github.com/apple/swift-protobuf/issues/1034
//      switch fieldNumber {
//      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.users) }()
//      default: break
//      }
//    }
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    if !self.users.isEmpty {
//      try visitor.visitRepeatedMessageField(value: self.users, fieldNumber: 1)
//    }
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_UserListResponse, rhs: User_UserListResponse) -> Bool {
//    if lhs.users != rhs.users {return false}
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_UserRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".UserRequest"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0")
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    while let fieldNumber = try decoder.nextFieldNumber() {
//      // The use of inline closures is to circumvent an issue where the compiler
//      // allocates stack space for every case branch when no optimizations are
//      // enabled. https://github.com/apple/swift-protobuf/issues/1034
//      switch fieldNumber {
//      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
//      default: break
//      }
//    }
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    if !self.userID.isEmpty {
//      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
//    }
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_UserRequest, rhs: User_UserRequest) -> Bool {
//    if lhs.userID != rhs.userID {return false}
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_GetCategoriesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".GetCategoriesRequest"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    // Load everything into unknown fields
//    while try decoder.nextFieldNumber() != nil {}
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_GetCategoriesRequest, rhs: User_GetCategoriesRequest) -> Bool {
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_Category: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".Category"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}icon\0")
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    while let fieldNumber = try decoder.nextFieldNumber() {
//      // The use of inline closures is to circumvent an issue where the compiler
//      // allocates stack space for every case branch when no optimizations are
//      // enabled. https://github.com/apple/swift-protobuf/issues/1034
//      switch fieldNumber {
//      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
//      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
//      case 3: try { try decoder.decodeSingularStringField(value: &self.icon) }()
//      default: break
//      }
//    }
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    if !self.id.isEmpty {
//      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
//    }
//    if !self.name.isEmpty {
//      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
//    }
//    if !self.icon.isEmpty {
//      try visitor.visitSingularStringField(value: self.icon, fieldNumber: 3)
//    }
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_Category, rhs: User_Category) -> Bool {
//    if lhs.id != rhs.id {return false}
//    if lhs.name != rhs.name {return false}
//    if lhs.icon != rhs.icon {return false}
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
//
//nonisolated extension User_GetCategoriesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
//  public static let protoMessageName: String = _protobuf_package + ".GetCategoriesResponse"
//  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}categories\0")
//
//  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
//    while let fieldNumber = try decoder.nextFieldNumber() {
//      // The use of inline closures is to circumvent an issue where the compiler
//      // allocates stack space for every case branch when no optimizations are
//      // enabled. https://github.com/apple/swift-protobuf/issues/1034
//      switch fieldNumber {
//      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.categories) }()
//      default: break
//      }
//    }
//  }
//
//  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
//    if !self.categories.isEmpty {
//      try visitor.visitRepeatedMessageField(value: self.categories, fieldNumber: 1)
//    }
//    try unknownFields.traverse(visitor: &visitor)
//  }
//
//  public static func ==(lhs: User_GetCategoriesResponse, rhs: User_GetCategoriesResponse) -> Bool {
//    if lhs.categories != rhs.categories {return false}
//    if lhs.unknownFields != rhs.unknownFields {return false}
//    return true
//  }
//}
